name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  POSTMAN_COLLECTION_ID: ${{ secrets.POSTMAN_COLLECTION_ID }}
  POSTMAN_API_KEY: ${{ secretes.POSTMAN_API_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    
    - name: Npm Install Dependencies
      run: npm install
        
    - name: run test
      run: node test.js

